spring.application.name=actividad-autonoma-pro3

spring.datasource.url=jdbc:mysql://localhost:3306/maxFood
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

